### ISSUE TITLE
Failed to load pull requests

### ISSUE THREAD

**Issue by andrewjswan** [my-badges/my-badges#72]
```
Failed to load pull requests
RequestError [HttpError]: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `D841:E6E1:6772D40:682F31A:67242405` when reporting this issue."}]}
    at fetchWrapper (file:///home/runner/.npm/_npx/7fb6944fbf6d75ed/node_modules/@octokit/request/dist-bundle/index.js:119:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (file:///home/runner/.npm/_npx/7fb6944fbf6d75ed/node_modules/@octokit/plugin-retry/dist-bundle/index.js:36:20)
    at async Job.doExecute (/home/runner/.npm/_npx/7fb6944fbf6d75ed/node_modules/bottleneck/light.js:405:18) {
  status: 502,
```
https://github.com/andrewjswan/andrewjswan/actions/runs/11622110394/job/32367041283#step:2:139

**Comment by antonmedv** [comment]
¯\\\_(ツ)_/¯

**Comment by andrewjswan** [comment]
```
Failed to load pull requests
RequestError [HttpError]: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `2019:CB565:3CC6F0D:77D2D7C:6747382D` when reporting this issue."}]}
    at fetchWrapper (file:///home/runner/.npm/_npx/7fb6944fbf6d75ed/node_modules/@octokit/request/dist-bundle/index.js:119:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestWithGraphqlErrorHandling (file:///home/runner/.npm/_npx/7fb6944fbf6d75ed/node_modules/@octokit/plugin-retry/dist-bundle/index.js:36:20)
    at async Job.doExecute (/home/runner/.npm/_npx/7fb6944fbf6d75ed/node_modules/bottleneck/light.js:405:18) {
  status: 502,
  request: {
    method: 'POST',
    url: 'https://api.github.com/graphql',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/0.0.0-development octokit-core.js/6.1.2 Node.js/18.20.5 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
```
https://github.com/andrewjswan/andrewjswan/actions/runs/11622110394/job/32367041283#step:2:139

**Comment by polRk** [comment]
Maybe check rate-limit headers? or add retry

**Comment by antonmedv** [comment]
I see similar behavior. Looks like something with GitHub api: 502

I added reties. my-badges will retry loading pulls 3 times. For me this worked.

**Comment by antonmedv** [comment]
Actually I think i know! We need to make pagination size smaller! Will try that.

**Comment by antonmedv** [comment]
I think I fixed it: https://github.com/my-badges/my-badges/commit/dc72393e5db7f09ef2dbcace49c89b4d516951ce
